name: "mysql-mgr-ha-experiment"
services:
  db1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db1
    environment:
      DB_PASSWORD: "test@1234"
    volumes:
      - /var/lib/mysql # 临时非持久化数据目录
      - ./conf/db1.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./ssl:/etc/mysql/ssl
    cap_add:
      - SYS_NICE # 允许容器执行 mbind

  db2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db2
    environment:
      DB_PASSWORD: "test@1234"
    volumes:
      - /var/lib/mysql # 临时非持久化数据目录
      - ./conf/db2.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./ssl:/etc/mysql/ssl:ro
    cap_add:
      - SYS_NICE # 允许容器执行 mbind

  db3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db3
    environment:
      DB_PASSWORD: "test@1234"
    volumes:
      - /var/lib/mysql # 临时非持久化数据目录
      - ./conf/db3.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./ssl:/etc/mysql/ssl:ro
    cap_add:
      - SYS_NICE # 允许容器执行 mbind


  # router:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: router
  #   ports:
  #     - "6446:6446"
  #   volumes:
  #     - /var/lib/mysql
  #     - ./conf/router.cnf:/etc/mysql/mysql-router.conf.d/mysqlrouter.conf:ro
